// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file spec.proto (package proto, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Any } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_any } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file spec.proto.
 */
export const file_spec: GenFile =
  /*@__PURE__*/
  fileDesc(
    "CgpzcGVjLnByb3RvEgVwcm90byKUAgoPVmFsaWRhdGlvbkVycm9yEgwKBGNvZGUYASABKAkSCwoDbXNnGAIgASgJEhgKEGRlZmF1bHRfdmlld19tc2cYBCABKAkSPwoQZmllbGRfdmlvbGF0aW9ucxgDIAMoCzIlLnByb3RvLlZhbGlkYXRpb25FcnJvci5GaWVsZFZpb2xhdGlvbhqKAQoORmllbGRWaW9sYXRpb24SDQoFZmllbGQYASABKAkSDAoEY29kZRgCIAEoCRINCgVwYXJhbRgDIAEoCRILCgNtc2cYBCABKAkSGAoQZGVmYXVsdF92aWV3X21zZxgGIAEoCRIlCgdwYXlsb2FkGAUgASgLMhQuZ29vZ2xlLnByb3RvYnVmLkFueWIGcHJvdG8z",
    [file_google_protobuf_any],
  );

/**
 * @generated from message proto.ValidationError
 */
export type ValidationError = Message<"proto.ValidationError"> & {
  /**
   * @generated from field: string code = 1;
   */
  code: string;

  /**
   * @generated from field: string msg = 2;
   */
  msg: string;

  /**
   * default_view_msg is the default display message in view(web/app) when an error occurs.
   *
   * @generated from field: string default_view_msg = 4;
   */
  defaultViewMsg: string;

  /**
   * Describes all violations in a client request.
   *
   * @generated from field: repeated proto.ValidationError.FieldViolation field_violations = 3;
   */
  fieldViolations: ValidationError_FieldViolation[];
};

/**
 * Describes the message proto.ValidationError.
 * Use `create(ValidationErrorSchema)` to create a new message.
 */
export const ValidationErrorSchema: GenMessage<ValidationError> =
  /*@__PURE__*/
  messageDesc(file_spec, 0);

/**
 * A message type used to describe a single bad request field.
 *
 * @generated from message proto.ValidationError.FieldViolation
 */
export type ValidationError_FieldViolation =
  Message<"proto.ValidationError.FieldViolation"> & {
    /**
     * A path leading to a field in the request body. The value will be a
     * sequence of dot-separated identifiers that identify a protocol buffer
     * field. E.g., "field_violations.field" would identify this field.
     *
     * @generated from field: string field = 1;
     */
    field: string;

    /**
     * @generated from field: string code = 2;
     */
    code: string;

    /**
     * @generated from field: string param = 3;
     */
    param: string;

    /**
     * A description of why the request element is bad.
     *
     * @generated from field: string msg = 4;
     */
    msg: string;

    /**
     * default_view_msg is the default display message in view(web/app) when an error occurs.
     *
     * @generated from field: string default_view_msg = 6;
     */
    defaultViewMsg: string;

    /**
     * Extension.
     *
     * @generated from field: google.protobuf.Any payload = 5;
     */
    payload?: Any;
  };

/**
 * Describes the message proto.ValidationError.FieldViolation.
 * Use `create(ValidationError_FieldViolationSchema)` to create a new message.
 */
export const ValidationError_FieldViolationSchema: GenMessage<ValidationError_FieldViolation> =
  /*@__PURE__*/
  messageDesc(file_spec, 0, 0);
