/**
 * Connect client template generator
 */

/**
 * Generate connect-client.ts content
 * This version uses lazy initialization pattern to allow external configuration
 */
export function generateConnectClientTemplate(): string {
  return `/**
 * Shared Connect-RPC transport configuration
 *
 * This module provides the configured transport used by all service clients.
 * The transport is configured via initializeTransport() which should be called
 * before using any service clients.
 */

import { createConnectTransport } from '@connectrpc/connect-web'
import type { Transport, Interceptor } from '@connectrpc/connect'

/**
 * Shared transport instance
 * Must be initialized via initializeTransport() before use
 */
let transportInstance: Transport | null = null

/**
 * Initialize the shared transport with custom configuration
 *
 * @param config - Transport configuration
 * @param config.baseUrl - Base URL for the service
 * @param config.fetch - Custom fetch function with middleware support
 * @param config.interceptors - Connect-RPC interceptors
 */
export function initializeTransport(config: {
  baseUrl?: string
  fetch: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>
  interceptors?: Interceptor[]
}): void {
  const { baseUrl, fetch, interceptors = [] } = config

  transportInstance = createConnectTransport({
    baseUrl: baseUrl || '',
    fetch,
    interceptors,
  })
}

/**
 * Get the shared transport instance
 * Throws error if transport is not initialized
 */
export function getTransport(): Transport {
  if (!transportInstance) {
    throw new Error(
      'Transport not initialized. Call initializeTransport() before using service clients.'
    )
  }
  return transportInstance
}

/**
 * Proxy-based transport export for backward compatibility
 * Allows using \`transport\` directly without calling getTransport()
 */
export const transport: Transport = new Proxy({} as Transport, {
  get(target, prop) {
    return Reflect.get(getTransport(), prop)
  },
}) as Transport

/**
 * Reset the transport (useful for testing)
 */
export function resetTransport(): void {
  transportInstance = null
}
`;
}

/**
 * Generate top-level index.ts that aggregates all modules
 */
export function generateRpcServiceIndexTemplate(modules: string[]): string {
  // For single module, only export default
  if (modules.length === 1) {
    const moduleName = modules[0];
    return `// RPC Service Index - Aggregates all service modules
// DO NOT EDIT: This file is automatically generated

export * as ${moduleName}Service from './${moduleName}/services'
`;
  }

  // For multiple modules, aggregate into default export
  return `// RPC Service Index - Aggregates all service modules
// DO NOT EDIT: This file is automatically generated

${modules.map((module) => `import * as ${module}Service from './${module}/services'`).join("\n")}

export default {
${modules.map((module) => `  ...${module}Service,`).join("\n")}
}
`;
}
