/**
 * Service wrapper generation utilities
 */
import fs from "fs";
import path from "path";
import type { ServiceInfo, MethodInfo } from "../types";

/**
 * Recursively find all *_pb.ts files in a directory
 * These files contain protobuf-generated types (messages, enums, schemas)
 *
 * @param dir - Directory to scan
 * @param baseDir - Base directory for relative path calculation
 * @returns Array of relative paths to _pb.ts files
 */
export function findAllTypeFiles(dir: string, baseDir?: string): string[] {
  const base = baseDir || dir;
  const results: string[] = [];

  if (!fs.existsSync(dir)) {
    return results;
  }

  const items = fs.readdirSync(dir);

  for (const item of items) {
    const fullPath = path.join(dir, item);
    const stat = fs.statSync(fullPath);

    if (stat.isDirectory()) {
      // Skip third-party directories
      if (
        item === "google" ||
        item === "buf" ||
        item === "connect" ||
        item === "protoc-gen-openapiv2" ||
        item === "validate" ||
        item === "relay"
      ) {
        continue;
      }
      results.push(...findAllTypeFiles(fullPath, base));
    } else if (item.endsWith("_pb.ts")) {
      // Get relative path from base directory
      const relativePath = path
        .relative(base, fullPath)
        .replace(/\\/g, "/")
        .replace(/\.ts$/, "");
      results.push(relativePath);
    }
  }

  return results.sort();
}

/**
 * Generate types/index.ts content that aggregates all type exports
 * This enables IDE auto-completion for pimService.types.*
 *
 * @param typeFiles - Array of relative paths to _pb.ts files (without .ts extension)
 * @returns Generated TypeScript code for types/index.ts
 */
export function generateTypesIndexFile(typeFiles: string[]): string {
  if (typeFiles.length === 0) {
    return `// Types Index - Auto-generated type aggregation
// DO NOT EDIT: This file is automatically generated

// No type files found
export {}
`;
  }

  const exports = typeFiles
    .map((file) => `export * from '../generated/${file}'`)
    .join("\n");

  return `// Types Index - Auto-generated type aggregation
// DO NOT EDIT: This file is automatically generated
//
// This file aggregates all protobuf-generated types for convenient access.
// Usage: import { pimService } from '@/lib/api'
//        const filter: pimService.types.ProductFilter = { ... }

${exports}
`;
}

/**
 * Extract all services from a service file
 * A single _pb.ts file may contain multiple services (e.g., CampaignService and CampaignAdminService)
 */
export function extractAllServiceInfo(
  filePath: string,
  generatedDir: string,
): ServiceInfo[] {
  const services: ServiceInfo[] = [];

  try {
    const content = fs.readFileSync(filePath, "utf-8");

    // Extract imports mapping (shared across all services in the file)
    const imports: Record<string, string> = {};
    const importRegex =
      /import\s+(?:type\s+)?\{([^}]+)\}\s+from\s+["']([^"']+)["']/g;
    let importMatch;
    while ((importMatch = importRegex.exec(content)) !== null) {
      const symbols = importMatch[1].split(",").map((s) => s.trim());
      const source = importMatch[2];
      symbols.forEach((s) => {
        if (s) imports[s] = source;
      });
    }

    // Get relative path from generated directory
    const relativePath = path
      .relative(generatedDir, filePath)
      .replace(/\\/g, "/")
      .replace(/\.ts$/, "");

    // Match ALL service definitions: export const ServiceName: GenService<{ ... }> = ...
    const serviceRegex = /export const (\w+):\s*GenService<{([\s\S]*?)}>\s*=/g;
    let serviceMatch;

    while ((serviceMatch = serviceRegex.exec(content)) !== null) {
      const serviceName = serviceMatch[1];
      const methodsBody = serviceMatch[2];
      const methods: MethodInfo[] = [];

      // Extract methods using regex
      // Matches: methodName: { ... input: typeof InputSchema; output: typeof OutputSchema; ... }
      const methodRegex =
        /(\w+):\s*\{\s*[\s\S]*?methodKind:\s*["']unary["'];\s*input:\s*typeof\s+(\w+)Schema;\s*output:\s*typeof\s+(\w+)Schema;/g;

      let methodMatch;
      while ((methodMatch = methodRegex.exec(methodsBody)) !== null) {
        methods.push({
          name: methodMatch[1],
          inputType: methodMatch[2], // e.g. GetBalanceRequest (without Schema)
          inputSchema: methodMatch[2] + "Schema", // e.g. GetBalanceRequestSchema
          outputType: methodMatch[3], // e.g. GetBalanceResponse (without Schema)
          outputSchema: methodMatch[3] + "Schema", // e.g. GetBalanceResponseSchema
        });
      }

      services.push({
        serviceName,
        importPath: relativePath,
        methods,
        imports,
      });
    }
  } catch (error) {
    console.warn(`⚠️  Warning: Could not parse ${filePath}`, error);
  }

  return services;
}

/**
 * Extract service name and methods from service file (legacy, returns first service only)
 * @deprecated Use extractAllServiceInfo instead
 */
export function extractServiceInfo(
  filePath: string,
  generatedDir: string,
): ServiceInfo | null {
  const services = extractAllServiceInfo(filePath, generatedDir);
  return services.length > 0 ? services[0] : null;
}

/**
 * Generate service wrapper code
 *
 * Simplified version that leverages Connect-RPC's built-in type inference.
 * The `Client<typeof Service>` type automatically infers all method signatures
 * from the service definition, eliminating the need for manual interface declarations.
 */
export function generateServiceWrapper(
  name: string,
  serviceInfo: ServiceInfo,
  moduleName?: string,
): string {
  const { serviceName, importPath } = serviceInfo;
  const camelName = name.charAt(0).toLowerCase() + name.slice(1);

  // Determine the relative path to connect-client and generated files
  const connectClientPath = moduleName
    ? "../../connect-client"
    : "../connect-client";
  const generatedPath = moduleName ? "../generated" : "../generated";

  return `// ${name} Service Client - Auto-generated
// DO NOT EDIT: This file is automatically generated

import { createClient, type Client } from '@connectrpc/connect'
import { ${serviceName} } from '${generatedPath}/${importPath}'
import { transport } from '${connectClientPath}'

/**
 * ${name} Service Client
 * Created using Connect-RPC's createClient with configured transport.
 * Type inference is automatically derived from ${serviceName} definition.
 */
export type ${name}Client = Client<typeof ${serviceName}>

export const ${camelName}Client: ${name}Client = createClient(${serviceName}, transport)
`;
}

/**
 * Generate services index file
 * Exports all service clients and the types namespace for IDE auto-completion
 */
export function generateServicesIndexFile(
  services: Array<{ name: string; camelName: string }>,
): string {
  return `// Services Index - Auto-generated exports
// DO NOT EDIT: This file is automatically generated

${services
  .map(
    (s) =>
      `export { ${s.camelName}Client, type ${s.name}Client } from './${s.camelName}.client'`,
  )
  .join("\n")}

// Export types namespace for IDE auto-completion
// Usage: pimService.types.ProductFilter, pimService.types.Product, etc.
export * as types from '../types'
`;
}

// generateServicesTypesFile is removed as it is no longer needed

/**
 * Check if a service name should be excluded based on patterns
 *
 * This function matches against the proto service name (e.g., "UserAdminService", "CampaignService")
 * Pattern examples:
 *   - "Admin" matches: UserAdminService, AdminService, ProductAdminService
 *   - "Admin$" matches: only services ending with "Admin" (not "AdminService")
 *   - "^Admin" matches: only services starting with "Admin"
 *
 * @param serviceName - The service name from proto definition (e.g., "UserAdminService")
 * @param excludePatterns - Array of regex patterns to match against service names
 */
function shouldExcludeService(
  serviceName: string,
  excludePatterns?: string[],
): boolean {
  if (!excludePatterns || excludePatterns.length === 0) {
    return false;
  }

  return excludePatterns.some((pattern) => {
    try {
      // Use regex to match service name
      // Pattern "Admin" will match any service containing "Admin" in its name
      const regex = new RegExp(pattern);
      return regex.test(serviceName);
    } catch {
      // If pattern is not a valid regex, treat it as a simple substring match
      return serviceName.includes(pattern);
    }
  });
}

/**
 * Generate service wrappers from scanned files
 */
export async function generateServiceWrappers(
  serviceFiles: string[],
  generatedDir: string,
  servicesDir: string,
  moduleName?: string,
  excludeServicePatterns?: string[],
): Promise<void> {
  // Ensure services directory exists
  if (!fs.existsSync(servicesDir)) {
    fs.mkdirSync(servicesDir, { recursive: true });
  }

  const generatedServices: Array<{ name: string; camelName: string }> = [];

  // Generate wrapper for each service file
  for (const filePath of serviceFiles) {
    // Skip third-party services (e.g., google, buf, connect)
    const normalizedPath = path.normalize(filePath);
    const pathSegments = normalizedPath.split(path.sep);
    if (
      pathSegments.includes("google") ||
      pathSegments.includes("buf") ||
      pathSegments.includes("connect")
    ) {
      continue;
    }

    // Extract ALL services from this file (a single _pb.ts may contain multiple services)
    const allServices = extractAllServiceInfo(filePath, generatedDir);
    if (allServices.length === 0) continue;

    for (const serviceInfo of allServices) {
      // Check if service should be excluded based on patterns
      if (
        shouldExcludeService(serviceInfo.serviceName, excludeServicePatterns)
      ) {
        console.log(
          `   ⏭️  Skipped ${serviceInfo.serviceName} (matches exclude pattern)`,
        );
        continue;
      }

      // Extract clean name (remove "Service" suffix if present)
      const cleanName = serviceInfo.serviceName.replace(/Service$/, "");
      const camelName = cleanName.charAt(0).toLowerCase() + cleanName.slice(1);

      const code = generateServiceWrapper(cleanName, serviceInfo, moduleName);

      const outputPath = path.join(servicesDir, `${camelName}.client.ts`);
      fs.writeFileSync(outputPath, code);
      console.log(`   ✅ Generated ${cleanName} client`);

      generatedServices.push({ name: cleanName, camelName });
    }
  }

  // Generate services index file (Clients and Types)
  if (generatedServices.length > 0) {
    const servicesIndexContent = generateServicesIndexFile(generatedServices);
    const servicesIndexPath = path.join(servicesDir, "index.ts");
    fs.writeFileSync(servicesIndexPath, servicesIndexContent);
    console.log(`   ✅ Generated services index (with types)`);

    // Removed generation of index.d.ts
  }

  console.log(`   📦 Total services generated: ${generatedServices.length}`);
}
